#pragma once
#include <opencv2\opencv.hpp>
#include <opencv2/highgui.hpp>
#include <opencv2\core.hpp>
#include <opencv2\cvconfig.h>
#include <opencv2\imgproc.hpp>
#include <opencv2\objdetect.hpp>
#include <opencv2\features2d.hpp>
#include <opencv2\features2d\features2d.hpp>
#include <opencv2\xfeatures2d.hpp>
